/** Russian UI catalog for the mini-app (single source of user-facing strings). */
export const ru = {
    appTitle: "Свои Правила",
    openFromTelegram: "Откройте приложение из Telegram",
    loading: "Загрузка…",
    errorGeneric: "Не удалось загрузить. Попробуйте ещё раз.",
    retry: "Повторить",
    close: "Закрыть",
    cancel: "Отмена",
    save: "Сохранить",
    add: "Добавить",
    gateIncomplete: "Завершите настройку в чате с ботом",
    gateConsentExtra: "Нужно подтвердить согласия в боте.",
    gateUnauthorized: "Откройте приложение заново из Telegram",
    contactsTitle: "Контакты",
    contactsEmpty: "Пока нет контактов. Добавьте человека, с которым хотите договориться.",
    contactsAdd: "Добавить контакт",
    contactsRename: "Переименовать",
    contactsMakeActive: "Сделать активным",
    contactsActiveBadge: "активный",
    contactsLabel: "Как называть",
    contactsRelationship: "Отношения",
    contactsLimit: "Достигнут лимит контактов.",
    contactAddRule: "Добавить правило",
    contactPairedBadge: "Общий свод",
    contactInvite: "Пригласить в общий свод",
    contactInviteExplain:
        "Отправьте ссылку партнёру — после принятия у вас появится общий свод правил.",
    contactInviteShare: "Поделиться",
    contactInviteCopy: "Копировать",
    contactInviteCopied: "Ссылка скопирована",
    contactLeavePair: "Выйти из общего свода",
    rulesPersonalTitle: "Личные правила",
    rulesSharedTitle: "Общие правила",
    ruleAwaitingPartner: "ждёт подтверждения партнёра",
    ruleApprove: "Подтвердить",
    ruleReject: "Отклонить",
    addRuleScope: "Свод",
    addRuleScopePersonal: "Личный",
    addRuleScopeShared: "Общий",
    privacyTitle: "Приватность",
    privacyExportAction: "Выгрузить данные",
    privacyExportDone: "Файл отправлен в чат с ботом",
    privacyExportUnavailable: "Напишите боту /start, затем повторите",
    privacyRevokeAction: "Отозвать согласия",
    privacyDeleteAction: "Удалить аккаунт",
    privacyDeleteForever: "Удалить навсегда",
    privacyDeleted: "Аккаунт удалён",
    rateLimited: "Слишком много запросов. Подождите немного.",
    suggestionsTitle: "Предложения",
    suggestionAccept: "Добавить",
    suggestionDismiss: "Не надо",
    rulesTitle: "Правила",
    rulesEmpty: "Правило — короткая договорённость, которую вы хотите помнить в разговоре.",
    ruleEffectiveSince: "действует с {date}",
    rulePendingEdit: "есть правка на согласовании",
    ruleProposed: "ждёт согласования",
    ruleArchive: "Архивировать",
    ruleArchiveConfirm: "Архивировать правило «{text}»?",
    addRuleTitle: "Новое правило",
    addRuleCategory: "Категория",
    addRuleText: "Текст",
    addRuleSubmit: "Сохранить правило",
    addRuleValidation: "Проверьте текст правила.",
    addRuleOpenLimit: "Слишком много открытых правил.",
    decodeEntry: "Расшифровать",
    decodeTitle: "Расшифровать",
    decodePlaceholder: "Вставьте сообщение, которое хотите понять",
    decodeSubmit: "Расшифровать",
    decodeAnalysis: "Разбор",
    decodeCopy: "Копировать",
    decodeInsert: "Вставить в чат",
    decodeMakeRule: "Сделать правилом",
    decodeSuggestionEdit: "Изменить",
    decodeRefused: "С этим лучше не помогать. Могу помочь сказать это уважительно.",
    decodeErrorBusy: "Расшифровка уже выполняется. Дождитесь окончания.",
    decodeErrorQuota: "Лимит расшифровок на час исчерпан. Попробуйте позже.",
    decodeErrorUnavailable: "Сейчас не получилось расшифровать. Попробуйте позже.",
    decodeErrorInvalid: "Не удалось разобрать ответ. Попробуйте ещё раз.",
    decodeErrorShort: "Слишком короткий текст.",
    decodeErrorLong: "Слишком длинный текст.",
    decodeSuggestNone: "Подходящего правила не нашлось.",
    decodeSuggestUnavailable: "Предложение больше недоступно.",
    decodeSuggestQuota: "Сервис временно недоступен из‑за лимита нагрузки.",
    decodeSuggestPending: "Уже есть предложение из расшифровки.",
    firmness: {
        gentle: "мягко",
        balanced: "ровно",
        firm: "твёрдо",
    },
    relationships: {
        partner: "Партнёр",
        family: "Семья",
        friend: "Друг",
        work: "Работа",
        other: "Другое",
    },
    categories: {
        taboo_topic: "Запретная тема",
        how_to_ask: "Как спрашивать",
        apology: "Извинения",
        conflict_protocol: "Конфликт",
        other: "Другое",
    },
} as const;

export type RuStrings = typeof ru;

export type RelationshipKey = keyof typeof ru.relationships;
export type CategoryKey = keyof typeof ru.categories;
