/** Russian UI catalog for the mini-app (single source of user-facing strings). */
export const ru = {
    appTitle: "Свои Правила",
    openFromTelegram: "Откройте приложение из Telegram",
    loading: "Загрузка…",
    errorGeneric: "Не удалось загрузить. Попробуйте ещё раз.",
    retry: "Повторить",
    close: "Закрыть",
    cancel: "Отмена",
    save: "Сохранить",
    continue: "Продолжить",
    gateUnauthorized: "Откройте приложение заново из Telegram",
    stepOf: "Шаг {current} из {total}",

    tabsLabel: "Разделы",
    tabHome: "Главная",
    tabPeople: "Люди",
    tabPrivacy: "Приватность",

    greetingMorning: "Доброе утро",
    greetingDay: "Добрый день",
    greetingEvening: "Добрый вечер",
    greetingNight: "Доброй ночи",
    homeTitle: "С кем сегодня важный разговор?",
    homeTalkingWith: "Сейчас говорю с",
    homeChange: "Сменить",
    homeChoose: "Выбрать",
    homeNoContactTitle: "Пока никого нет рядом",
    homeNoContactText: "Добавьте человека, с которым хотите договориться, — во вкладке «Люди».",
    homeNoActiveTitle: "С кем сегодня разговор?",
    homeNoActiveText: "Выберите человека — подсказки и правила будут учитывать именно его.",
    homeDecodeTitle: "Расшифровать сообщение",
    homeDecodeText:
        "Вставьте, что вам написали — подскажем, что за этим может стоять и как ответить спокойно.",
    homeDecodeCta: "Вставить и разобрать",
    homeSuggestionLabel: "Новое предложение",
    homeInlineHintTitle: "Подсказка прямо в переписке",
    homeInlineHintBefore: "Наберите ",
    homeInlineHintAfter:
        " и черновик в любом чате — появятся мягкие варианты ответа. Текст не сохраняется.",
    pickerTitle: "С кем разговор",
    pickerEmpty: "Пока нет контактов.",

    onboardingTagline: "Помогает сказать трудное — и помнит, о чём вы договорились.",
    onboardingFeatureDecodeLead: "Расшифровать.",
    onboardingFeatureDecode: "Поймёте, что стоит за резкой фразой, и ответите без ссоры.",
    onboardingFeatureRulesLead: "Правила.",
    onboardingFeatureRules: "Короткие договорённости с близкими — бот учтёт их в подсказках.",
    onboardingFeaturePrivateLead: "Приватно.",
    onboardingFeaturePrivate: "Переписку не храним, правила зашифрованы.",
    onboardingAgeCheckbox: "Мне исполнилось 18 лет",
    onboardingConsentTitle: "Что мы храним — и что нет",
    onboardingConsentLead: "Коротко и честно. Полные тексты — по ссылкам.",
    onboardingStoreEncrypted:
        "Контакты и правила — в зашифрованном виде, ключ только у вашей учётной записи.",
    onboardingStoreStats: "Обезличенная статистика: сколько раз пользовались, без текстов.",
    onboardingStoreNever: "Переписку и черновики не сохраняем нигде.",
    onboardingViaBot:
        "Ответ, вставленный из подсказки в чате, Telegram подписывает «via @{bot}» — собеседник это увидит.",
    onboardingAccept: "Принять и начать",
    consentDocLink: "Текст согласия",
    consentDocsClose: "Закрыть",
    consentKinds: {
        personal_data: "Хранение контактов и правил",
        special_category: "Обработка текста для подсказок",
    },

    inviteTitle: "Вас приглашают вести общий свод правил",
    inviteLead: "Договорённости, которые помнят оба.",
    inviteStepShared: "Общие правила видите вы оба. Личные остаются личными.",
    inviteStepConfirm: "Правило начинает действовать, когда его подтвердили оба.",
    inviteStepLeave: "Выйти можно в любой момент — каждый сохранит свои формулировки.",
    inviteExpires: "Ссылка действует до {date}",
    inviteLabel: "Как называть этого человека",
    inviteRelationship: "Кем для вас этот человек?",
    inviteAccept: "Принять приглашение",
    inviteLater: "Не сейчас",
    inviteInvalid: "Приглашение недействительно или уже использовано.",
    inviteExpired: "Срок приглашения истёк.",
    inviteOwn: "Нельзя принять собственное приглашение.",

    contactsTitle: "Люди",
    contactsLead: "С кем вы договариваетесь. Откройте человека, чтобы увидеть правила.",
    contactsEmpty: "Пока нет контактов. Добавьте человека, с которым хотите договориться.",
    contactsAdd: "Добавить контакт",
    contactsRename: "Переименовать",
    contactsMakeActive: "Сделать активным",
    contactsActiveBadge: "активный",
    contactsLabel: "Как называть",
    contactsRelationship: "Отношения",
    contactsLimit: "Достигнут лимит контактов.",
    contactEdit: "Изменить контакт",
    contactAddRule: "Добавить правило",
    contactPairedBadge: "Общий свод",
    contactInvite: "Пригласить в общий свод",
    contactInviteExplain:
        "Отправьте ссылку партнёру — после принятия у вас появится общий свод правил.",
    contactInviteShare: "Поделиться",
    contactInviteCopy: "Копировать",
    contactInviteCopied: "Ссылка скопирована",
    contactLeavePair: "Выйти из общего свода",
    contactLeaveNote: "Каждый сохранит правила, которые сформулировал сам. Попросим подтвердить.",
    rulesPersonalTitle: "Личные правила",
    rulesPersonalNote: "— видите только вы",
    rulesSharedTitle: "Общие правила",
    ruleAwaitingPartner: "ждёт подтверждения партнёра",
    ruleNeedsApproval: "{name} предлагает · нужно ваше «да»",
    ruleApprove: "Подтвердить",
    ruleReject: "Отклонить",
    addRuleScope: "Чьё правило",
    addRuleScopePersonal: "Только моё",
    addRuleScopeShared: "Общее для двоих",
    addRuleSharedNote: "Общее правило начнёт действовать, когда второй человек его подтвердит.",
    privacyTitle: "Приватность",
    privacyLead: "Ваши данные — ваши. Всё управляется здесь.",
    privacyExportAction: "Скачать мои данные",
    privacyExportDone: "Файл сохранён",
    privacyExportFailed: "Не удалось скачать файл. Попробуйте ещё раз.",
    privacyExportUnavailable: "Сервис временно недоступен. Попробуйте позже.",
    privacyConsentsAction: "Тексты согласий",
    privacyConsentsHint: "Что и зачем мы обрабатываем",
    privacyRevokeAction: "Отозвать согласия",
    privacyDeleteAction: "Удалить аккаунт",
    privacyDeleteButton: "Удалить…",
    privacyDeleteForever: "Удалить навсегда",
    privacyDeleted: "Аккаунт удалён",
    rateLimited: "Слишком много запросов. Подождите немного.",
    suggestionsTitle: "Предложения",
    suggestionAccept: "Добавить",
    suggestionDismiss: "Не надо",
    rulesTitle: "Правила",
    rulesEmpty: "Правило — короткая договорённость, которую вы хотите помнить в разговоре.",
    ruleEffectiveSince: "действует с {date}",
    rulePendingEdit: "есть правка на согласовании",
    ruleProposed: "ждёт согласования",
    ruleArchive: "Архивировать",
    ruleArchiveConfirm: "Архивировать правило «{text}»?",
    addRuleTitle: "Новое правило",
    addRuleFor: "Для: {label}",
    addRuleText: "О чём договорились",
    addRuleHint: "Коротко и по делу — так проще помнить",
    addRuleCategory: "Тема",
    addRuleSubmit: "Сохранить правило",
    addRuleSubmitShared: "Предложить правило",
    addRuleValidation: "Проверьте текст правила.",
    addRuleOpenLimit: "Слишком много открытых правил.",

    decodeTitle: "Расшифровать",
    decodeLead: "Вставьте сообщение, которое задело или озадачило.",
    decodeFrom: "Пишет {name}",
    decodeFromNone: "Выбрать, кто пишет",
    decodeField: "Сообщение",
    decodePlaceholder: "Вставьте сообщение, которое хотите понять",
    decodePaste: "Вставить из буфера",
    decodePasteFailed: "Не удалось прочитать буфер обмена. Вставьте текст вручную.",
    decodePrivacyNamed: "Текст не сохраняется. Учтём ваши правила с {name}.",
    decodePrivacy: "Текст не сохраняется.",
    decodeSubmit: "Разобрать",
    decodeRemaining: {
        one: "Сегодня остался {count} разбор",
        few: "Сегодня осталось {count} разбора",
        many: "Сегодня осталось {count} разборов",
    },
    decodeIncoming: "Входящее сообщение",
    decodeAnalysis: "Что за этим может стоять",
    decodeReplies: "Как можно ответить",
    decodeCopy: "Копировать",
    decodeInsert: "Вставить в чат",
    decodeRuleTitle: "Повторяется? Договоритесь заранее",
    decodeRuleText: "Предложим правило по этому разговору — вы решите, оставить ли его.",
    decodeMakeRule: "Сделать правилом",
    decodeAgain: "Разобрать другое",
    decodeSuggestionEdit: "Изменить",
    decodeRefused: "С этим лучше не помогать. Могу помочь сказать это уважительно.",
    decodeErrorBusy: "Расшифровка уже выполняется. Дождитесь окончания.",
    decodeErrorQuota: "Лимит расшифровок на час исчерпан. Попробуйте позже.",
    decodeErrorUnavailable: "Сейчас не получилось расшифровать. Попробуйте позже.",
    decodeErrorInvalid: "Не удалось разобрать ответ. Попробуйте ещё раз.",
    decodeErrorShort: "Слишком короткий текст.",
    decodeErrorLong: "Слишком длинный текст.",
    decodeSuggestNone: "Подходящего правила не нашлось.",
    decodeSuggestUnavailable: "Предложение больше недоступно.",
    decodeSuggestPending: "Уже есть предложение из расшифровки.",

    limitTitleQuota: "На сегодня разборы закончились",
    limitTitleBudget: "Сервис временно перегружен",
    limitNote: "Правила и подсказки в чатах по-прежнему с вами.",
    limitHelpBefore: "Если сейчас очень тяжело — ",
    limitHelpLink: "помощь доступна всегда",
    limitHelpAfter: ", без лимитов.",
    limitOk: "Понятно",

    crisisTitle: "Похоже, вам сейчас очень тяжело",
    crisisSupport: "Вы не одни: с этим помогают люди, которые умеют слушать.",
    crisisEmergencyTitle: "Экстренная помощь — 112",
    crisisEmergencyHint: "Если есть угроза жизни",
    crisisAlways: "Этот экран доступен всегда — даже когда лимиты на сегодня исчерпаны.",
    crisisBack: "Вернуться",

    firmness: {
        gentle: "мягко",
        balanced: "ровно",
        firm: "твёрдо",
    },
    relationships: {
        partner: "Партнёр",
        family: "Семья",
        friend: "Друг",
        work: "Работа",
        other: "Другое",
    },
    categories: {
        taboo_topic: "Запретная тема",
        how_to_ask: "Как спрашивать",
        apology: "Извинения",
        conflict_protocol: "Конфликт",
        other: "Другое",
    },
} as const;

export type RuStrings = typeof ru;

export type RelationshipKey = keyof typeof ru.relationships;
export type CategoryKey = keyof typeof ru.categories;
