/** Russian UI catalog for the mini-app (single source of user-facing strings). */
export const ru = {
    appTitle: "Свои Правила",
    openFromTelegram: "Откройте приложение из Telegram",
    loading: "Загрузка…",
    errorGeneric: "Не удалось загрузить. Попробуйте ещё раз.",
    retry: "Повторить",
    close: "Закрыть",
    cancel: "Отмена",
    save: "Сохранить",
    add: "Добавить",
    gateIncomplete: "Завершите настройку в чате с ботом",
    gateConsentExtra: "Нужно подтвердить согласия в боте.",
    gateUnauthorized: "Откройте приложение заново из Telegram",
    contactsTitle: "Контакты",
    contactsEmpty: "Пока нет контактов. Добавьте человека, с которым хотите договориться.",
    contactsAdd: "Добавить контакт",
    contactsRename: "Переименовать",
    contactsMakeActive: "Сделать активным",
    contactsActiveBadge: "активный",
    contactsLabel: "Как называть",
    contactsRelationship: "Отношения",
    contactsLimit: "Достигнут лимит контактов.",
    contactDetailTitle: "Контакт",
    contactAddRule: "Добавить правило",
    suggestionsTitle: "Предложения",
    suggestionAccept: "Добавить",
    suggestionDismiss: "Не надо",
    rulesTitle: "Правила",
    rulesEmpty: "Правило — короткая договорённость, которую вы хотите помнить в разговоре.",
    ruleEffectiveSince: "действует с {date}",
    rulePendingEdit: "есть правка на согласовании",
    ruleProposed: "ждёт согласования",
    ruleArchive: "Архивировать",
    ruleArchiveConfirm: "Архивировать правило «{text}»?",
    addRuleTitle: "Новое правило",
    addRuleCategory: "Категория",
    addRuleText: "Текст",
    addRuleSubmit: "Отправить",
    addRuleValidation: "Проверьте текст правила.",
    addRuleOpenLimit: "Слишком много открытых правил.",
    relationships: {
        partner: "Партнёр",
        family: "Семья",
        friend: "Друг",
        work: "Работа",
        other: "Другое",
    },
    categories: {
        taboo_topic: "Запретная тема",
        how_to_ask: "Как спрашивать",
        apology: "Извинения",
        conflict_protocol: "Конфликт",
        other: "Другое",
    },
} as const;

export type RuStrings = typeof ru;

export type RelationshipKey = keyof typeof ru.relationships;
export type CategoryKey = keyof typeof ru.categories;
